#!/usr/bin/python3

user = input("What is your name?")

print("Welcome to python", user)

age = input("Please enter your age: "
print("ex: 20")
if age == 22 :
  print("You were born in 2000.")
elif age < 21 :
  print("Sorry, you're not old enough to buy alcohol.")
 else age <= 21 :
  print("You've come a long way. You should be proud of yourself."
